services:
  - type: web
    name: contribution-graph-pop-quiz
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
